### ISSUE TITLE
Convert to Jekyll app

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/landscape-brochure.internal#10]

**Comment by anthonydillon** [comment]
Should this be an epic?

**Comment by anasereijo** [comment]
@nottrobin is this still relevant?

**Comment by anthonydillon** [comment]
@anasereijo I would hold off doing any work on this until we know what the plan is for this project.

**Comment by nottrobin** [comment]
@anthonydillon why is the plan for this project in question?

**Comment by anthonydillon** [comment]
We need to work out a plan to have this hosted and proxyed by the landscape application. They seem resistant so not sure its worth spending to much time on it until we can iron out the hosting.

**Comment by anasereijo** [comment]
@anthonydillon still on hold?

**Comment by anasereijo** [comment]
closing this. we will create cards if this is required later
