### ISSUE TITLE
[Suggestion] small design change

### ISSUE THREAD

**Issue by mikeroyal** [canonical-web-and-design/landscape-brochure.internal#22]
I had a suggestion for the top bar to be black to match the overall design them seen on other canonical product website like snapcraft and MAAS. 

Make the top bar black
![landscape](https://user-images.githubusercontent.com/45159366/56839611-259cc880-6838-11e9-981a-1cdb588c1ed2.png)

![ubuntu](https://user-images.githubusercontent.com/45159366/56839903-a8725300-6839-11e9-933d-83e6010a1c2f.png)

**Comment by matthewpaulthomas** [comment]
Thanks for the suggestion. It’s a possibility that we settle on black for all product sites. But Landscape’s top bar is not an outlier at the moment. [Livepatch](https://auth.livepatch.canonical.com/) uses purple, [Juju](https://jujucharms.com/) uses green, [Blog](https://blog.ubuntu.com/) and [canonical.com](https://www.canonical.com/) use white, and various other sites (such as [USN](https://usn.ubuntu.com/) and [Developer](https://developer.ubuntu.com/)) use orange.

One viewpoint is that as the sites become more consistent in layout, it’s more useful for them to be different colours, making it easier to recognise that you are on a different site with different navigation.

**Comment by mikeroyal** [comment]
Hi @matthewpaulthomas, I agree that makes sense. :)

**Comment by anthonydillon** [comment]
Closing this as agreed but will address this with the next redesign of landscape website.
